### PR TITLE
Compile on debian squeeze.

### PR DESCRIPTION
**Pull request by thierryOrdissimo**
Hello,
we like very much your plugin that works well on wheezy. We made some work to compile it on squeeze, for which we have about 30 000 customers running it. Here you will find the patch that we hope you'll be able to integrate on  your main tree so we don't have to patch the sources of every new version. I does not change anything in the behaviour, it just make it compile on squeeze.
If you have any problem, feel free to contact us.
Regards

### CODE REVIEW

**Comment by i-rinat** [comment]
Ok, I've incorporated some changes which should not break anything else. But there are still some to go.
I really don't like `#ifdef` macros across the code, they are making code error prone. I also don't like to switch to a deprecated functions: those can disappear in a next version and there will be compatibility pain again.

**Comment by i-rinat** [comment]
I've made changes and it now compiles both in my current OS and Debian Squeeze chroot (with both stock glib and glib 2.26, which have dbus interface). Can you check whenever last version in `master` branch works for you too?

**Comment by thierryOrdissimo** [comment]
Thank you. I checked every change and everything is OK for me.
Good bye

**Comment by i-rinat** [comment]
OK, great. I'm closing this then.

**Pull request closed without merging**
