### PR TITLE
Debian branch for freshplayerplugin

### PR DESCRIPTION
**Pull request by basti12203**
I have debianzie this, so other user can simply build and install freshplayerplugin as debian package.
At the moment its only done for firefox (iceweasel).
One think you must to know:
If you update your pepperflashplayer via
 update-pepperflashplugin-nonfree
you musst run
 dpkg-reconfigure freshplayerplugin

An other problem on my debian jessie is:
When I uninstall pepperflashplugin-nonfree and try to reinstall, the package is reinstalled but
/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so is not downloaded again.

### CODE REVIEW

**Comment by i-rinat** [comment]
Sorry, no.

I have objections against keeping distribution-specific files in the source tree. Having `debian/` directory in upstream source makes package maintainer work harder. Exceptions are so-called native packages, which are developed as a part Debian itself, where a developer is the maintainer.

**Comment by i-rinat** [comment]
Also if I merge this, it will delete all source :-)

**Comment by MALLER-LAGOON** [comment]
@basti12203 im a debian user too, and instead what u propose, i rather prefer [this way](https://github.com/MALLER-LAGOON/Freshplayer-installer) to update and/or install the freshplayer.
by other hand, u can always edit the <code>~/.config/freshwrapper.conf</code> and add the new path to the <code>libpepflashplayer.so</code>

**Comment by basti12203** [comment]
@i-rinat: That you don't want to habe /debian in upstream i can understand. You can use it as a new branch, so you have a clean master and anybody how like can merge the debian brunch in there local working dir.

An other suggestion is that you can use tags, very time you "release" a new version like v0.2.1, v0.2.2 so it can be easier to build versions.

It doesn't matter, so I use it for my own.

**Comment by ericfowler303** [comment]
http://pastebin.com/5tiEKcaz

This is the bash script I use to rebuild mine, tweak it to your uses. I do use the nonfree package so it gets picked up without needing to use the .conf file. Lemme know what you think.

**Comment by i-rinat** [comment]
@basti12203, keeping a separate branch doesn't make any sense. It's not even about branching from current point and deleting all sources; there is a way to keep multiple roots in git tree, so one branch could contain absolutely independent set of files from the other one (see "git orphaned branch"). The reason is when you checkout one branch, git overwrites all files from other branches in a working copy. So you'll have either source code or debian subdirectory, not both at the same time.

> An other suggestion is that you can use tags, every time you "release" a new version like v0.2.1, v0.2.2 so it can be easier to build versions.

I already use tags to mark releases, checkout output of `git tag -l` command. Tarballs on release pages are actually generated by Github from tags.

> Is there a way to keep a fork in sync?

You can keep two repositories. One for freshplayerplugin source (`/repo1`), other for your packaging files (`/repo2`). Add `debian` directory to ignore list in repo1 by adding `debian` line to `/repo1/.git/info/exclude`, then create symlink `/repo2/debian -> /repo1/debian`. You'll be able to update repo1 freely, change repo2, and build packages without any interference.

**Comment by MALLER-LAGOON** [comment]
@basti12203 [watch this fork](https://github.com/andykimpe/freshplayerplugin).

**Comment by i-rinat** [comment]
Closing this one, as I'm not going to merge it.

**Comment by basti12203** [comment]
thank you. 
sorry for the inconvenience.

**Pull request closed without merging**
